### ISSUE TITLE
`linkAssets` should not copy *.map files from `vendor/swagger-api/swagger-ui/dist`

### ISSUE THREAD

**Issue by ga-tb** [harmbandstra/swagger-ui-bundle#14]
This code copies all files from `swagger-api/swagger-ui/dist` to `harmbandstra/swagger-ui-bundle/src/Resources/public/`

```
        $source = sprintf('%s/swagger-api/swagger-ui/dist', $vendorDir);
        $target = sprintf('%s/harmbandstra/swagger-ui-bundle/src/Resources/public', $vendorDir);

        $filesystem->mirror($source, $target, null, ['override' => true]);
```

Total of 9.2Mb. However the `*.map` files aren't really required, and the payload can be reduced to 2.2Mb by excluding them.

Will submit PR to get your opinion. Maybe there is a use-case I have not thought of.

**Comment by ga-tb** [comment]
PR: https://github.com/harmbandstra/swagger-ui-bundle/pull/15

**Comment by harmbandstra** [comment]
Hi, sorry for the late reply. Thanks for the PR! Looks like a valid improvement. I'll try to review/merge this weekend. Cheers.
