### ISSUE TITLE
Why is index.html being read from vendor ?

### ISSUE THREAD

**Issue by RiseAndCry** [harmbandstra/swagger-ui-bundle#16]
What's the point of `HarmBandstra\\SwaggerUiBundle\\Composer\\ScriptHandler::linkAssets` if DocsController (indexAction) uses `/vendor/swagger-api/swagger-ui/dist/index.html` anyway ?
i mean, shouldn't it use `/public/bundles/hbswaggerui/index.html` ?

**Comment by harmbandstra** [comment]
`linkAssets` also copies css and js files. But you have a point, it might be more logical to use `/public/bundles/hbswaggerui/index.html`
I'll see if I can change this somewhere in the near future. You're also welcome to open a PR ;-)
