### ISSUE TITLE
Assets pointing to incorrect path

### ISSUE THREAD

**Issue by ricohumme** [harmbandstra/swagger-ui-bundle#17]
Hi,

Is it a correct assumption that the assets are loaded as `./<asset>` ?
The index.html seems to load the asset from it's relative path (in my case `/api/docs`) instead of from it's original location (path of the index.html file)

The asset trying to be loaded is `/api/docs/swagger-ui.css` while the asset is actually stored in `/bundles/hbswaggerui/swagger-ui.css`.

Interested in your thoughts on this.

**Comment by h0mjam** [comment]
Into _DocsController_ contain action _redirectAction_, he redirect unknown file to bundle assets.

**Comment by harmbandstra** [comment]
@ricohumme @h0mjam is correct. If a file is not specified as a swagger file, it is redirected to the `/bundles/hbswaggerui/` directory.

**Comment by Denissimo** [comment]
I have the same problem.
@harmbandstra , @h0mjam  help plz

https://stackoverflow.com/questions/66155491/why-swagger-doesnt-see-files-in-public-bundles-hbswaggerui
