### ISSUE TITLE
Vendor write access

### ISSUE THREAD

**Issue by cdaguerre** [harmbandstra/swagger-ui-bundle#2]
What's the point in copying `swagger-api/swagger-ui/dist` to `swagger-api/swagger-ui/dist/Resources/public` [here](https://github.com/harmbandstra/swagger-ui-bundle/blob/master/src/Controller/DocsController.php#L32)?
It requires write access for the web server user to the vendor dir, which is not a good practise and isnt even necessary.  You could serve the file directly from `swagger-api/swagger-ui/dist`...

**Comment by harmbandstra** [comment]
Hi Christian, thanks for the PR. The files are copied there because I didn't really like adding extra configuration to the composer.json. But, I have to admit, this is a cleaner solution than the current one. I'll merge the PR and bump a major version.
