### ISSUE TITLE
Support for swagger-ui config options

### ISSUE THREAD

**Issue by oliver-ideahq** [harmbandstra/swagger-ui-bundle#21]
It would be great to be able to configure all / some of the [swagger-ui config options](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#parameters), e.g. `operationsSorter` via the bundle configuration `config/packages/hb_swagger_ui.yaml`, as an additional option, e.g. `swagger_ui_config`.

I'd be happy to supply a PR, if there's a chance to get this merged.

**Comment by harmbandstra** [comment]
Hi Oliver, that sounds like a valid extension to current functionality. I think it would be nicest to be able to add a configuration file, and specify this in the bundle configuration. If a config file is specified it should automatically be passed as a `configUrl=...` query parameter.
You're welcome to submit a PR for this. And if not, I might add it myself. Unfortunately I can't tell you when that would be ;-)
