### ISSUE TITLE
Move to swagger-ui 4

### ISSUE THREAD

**Issue by jokaorgua** [harmbandstra/swagger-ui-bundle#25]
I think would be great to move to swagger-ui v4 instead of using v3

**Comment by harmbandstra** [comment]
Hi jokaorgua, thanks for the feedback. I plan to push an update out soon, addressing both your issues.

**Comment by harmbandstra** [comment]
I published a new version `5.0.0` which uses swagger-ui v4. Let me know if you encounter any issues.
