### ISSUE TITLE
Compatibility issue with symfony 2.3 - 2.6 : Call to undefined method DocsController::getParameter()

### ISSUE THREAD

**Issue by quent57** [harmbandstra/swagger-ui-bundle#4]
This bundle require symfony/framework-bundle: ~2.3|~3.0.
From symfony 2.3, and up to 2.6 , the method getParameter doesn’t exist in Controller class.
cf https://symfony.com/blog/new-in-symfony-2-7-productivity-improvements

So, there is a execution time error here : https://github.com/harmbandstra/swagger-ui-bundle/blob/master/src/Controller/DocsController.php#L25 : 
> Exception: Call to undefined method HarmBandstra\SwaggerUiBundle\Controller\DocsController::getParameter()

**Comment by quent57** [comment]
Solution seem to write 
>            $specFiles = $this->container->getParameter('hb_swagger_ui.files');
instead of 
>            $specFiles = $this->getParameter('hb_swagger_ui.files');

**Comment by harmbandstra** [comment]
Thanks for the feedback. I released a patch which should resolve the issue (1.0.2).

**Comment by quent57** [comment]
Thank you for your reactivity !
