### ISSUE TITLE
Uncompatibility with incenteev/composer-parameter-handler

### ISSUE THREAD

**Issue by quent57** [harmbandstra/swagger-ui-bundle#5]
incenteev/composer-parameter-handler is widely used (close to 20 000 000 installs).
It depends on composer/composer: 1.0.*@dev : https://packagist.org/packages/incenteev/composer-parameter-handler
Whereas harmbandstra/swagger-ui-bundle depends on composer/composer: ^1.4 .
Could you lower the requirements in order to be compatible with composer/composer: 1.0.*@dev ?

**Comment by harmbandstra** [comment]
Thanks for the feedback. I released a patch which should resolve the issue (1.0.1).
