### ISSUE TITLE
'kernel.root_dir' is not good reference point for accessing the /vendor folder

### ISSUE THREAD

**Issue by Vorta** [harmbandstra/swagger-ui-bundle#9]
Hello!

I'm developing a multi-kernel symfony app that is essentially 2 apps in one. Each has its own swagger doc. Due to that, Kernel.php is no longer positioned in `src/`. Instead it is in `src/APP1/Kernel.php` and `src/APP2/Kernel.php`.

However, `HarmBandstra\SwaggerUiBundle\Controller\DocsController` has a line:
`$indexFilePath = $this->getParameter('kernel.root_dir') . '/../vendor/swagger-api/swagger-ui/dist/index.html';` which is broken due to kernel's different location and cannot be fixed from outside.
Symfony 3 and 4 allow kernels to be in different locations, so using kernel's root dir to find the vendor dir won't work in all cases.

Suggestion:
Use `$indexFilePath = $this->getParameter('kernel.project_dir') . '/vendor/swagger-api/swagger-ui/dist/index.html';`

This way the location of Kernel files will not break the operation of Swagger.

**Comment by harmbandstra** [comment]
Hi Vorta, thanks for reporting this. I'll look into it.

**Comment by harmbandstra** [comment]
Hi Vorta, I bumped to version 3.0 for multi-kernel support. Can you please test? Cheers.
